name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.6

      - name: Build the Docker image
        run: docker-compose build

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker tag go-backend ${{ secrets.DOCKER_USERNAME }}/icampus:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/icampus:latest

      - name: Deploy to server
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no lmj@widealpha.top 'docker pull ${{ secrets.DOCKER_USERNAME }}go-backend:latest && docker-compose up -d'
